import Link from "next/link";
import { db } from "@/lib/db";
import { requireOperationsUser } from "@/lib/require-user";
import DisputeActions from "./dispute-actions";
import { canPerform } from "@/lib/permissions";
import { dateTime, money, stateLabel } from "@/lib/presentation";

export default async function AuditPage({ searchParams }: { searchParams: Promise<{ view?: string; id?: string }> }) {
  const session = await requireOperationsUser();
  const params = await searchParams;
  const view = params.view === "events" || params.view === "sensitive" ? params.view : "disputes";
  const [disputes, events, sensitive] = await Promise.all([
    db.dispute.findMany({ where: { status: { in: ["OPEN", "UNDER_REVIEW"] } }, include: { auction: true, reporter: { select: { name: true } } }, orderBy: { createdAt: "asc" } }),
    db.auditEvent.findMany({ include: { auction: true, actor: { select: { name: true, role: true } } }, orderBy: { createdAt: "desc" }, take: 100 }),
    db.auction.findMany({ where: { sensitive: true }, orderBy: { createdAt: "desc" }, take: 30 }),
  ]);
  const selected = disputes.find((item) => item.id === params.id) ?? disputes[0];
  return <main className="simple-page"><div className="heading-row"><div><h1>Audit and disputes</h1><p className="muted">Review employee concerns, sensitive assets, and recorded decisions.</p></div><span className="listing-state">{disputes.length} open {disputes.length === 1 ? "dispute" : "disputes"}</span></div><nav className="record-tabs" aria-label="Compliance views">{[["disputes", "Open disputes"], ["events", "Audit events"], ["sensitive", "Sensitive assets"]].map(([key, label]) => <Link href={`/operations/audit?view=${key}`} key={key} aria-current={view === key ? "page" : undefined}>{label}</Link>)}</nav>
    {view === "disputes" && <div className="workspace-columns"><section className="workspace-panel"><h2>Review queue</h2>{disputes.length ? <div className="activity-list">{disputes.map((dispute) => <Link key={dispute.id} href={`/operations/audit?id=${dispute.id}`} aria-current={selected?.id === dispute.id ? "true" : undefined} className={`activity-row ${selected?.id === dispute.id ? "selected-record" : ""}`}><div><strong>{dispute.auction.title}</strong><span>{dispute.reason}</span><small>{dispute.reporter.name} · {dateTime(dispute.createdAt)} WAT</small></div><div className="activity-value"><span className="listing-state">{stateLabel(dispute.status)}</span><small>{dispute.auction.reference}</small></div></Link>)}</div> : <p className="empty-copy">No open disputes. New employee submissions will appear here.</p>}</section><aside className="support-column review-evidence">{selected && <section className="workspace-panel"><h2>{selected.auction.title}</h2><dl className="facts"><div><dt>Auction</dt><dd>{selected.auction.reference}</dd></div><div><dt>Status</dt><dd>{stateLabel(selected.auction.state)}</dd></div><div><dt>Current price</dt><dd>{money(selected.auction.currentBid || selected.auction.startingPrice)}</dd></div><div><dt>Submitted by</dt><dd>{selected.reporter.name}</dd></div></dl><div className="dispute-detail"><h3>{selected.reason}</h3><p>{selected.detail}</p>{selected.evidenceKey && <a className="outline-button" href={`/api/uploads/download?key=${encodeURIComponent(selected.evidenceKey)}`} target="_blank" rel="noreferrer">View submitted evidence</a>}{selected.resolution && <p><strong>Latest response:</strong> {selected.resolution}</p>}</div>{canPerform(session.user.role, "COMPLIANCE") ? <DisputeActions key={selected.id} disputeId={selected.id} /> : <p className="muted">Compliance can record a decision for this dispute.</p>}</section>}<section className="workspace-panel"><h2>Recent audit events</h2>{events.slice(0, 5).map((event) => <div className="audit-entry" key={event.id}><strong>{stateLabel(event.action)}</strong><small>{event.actor?.name ?? "System"} · {dateTime(event.createdAt)} WAT</small></div>)}{!events.length && <p className="muted">No events recorded yet.</p>}<Link className="text-link" href="/operations/audit?view=events">View audit trail</Link></section></aside></div>}
    {view === "sensitive" && <section className="workspace-panel"><h2>Sensitive assets</h2><p className="muted">Latest 30 sensitive listings. Wipe evidence applies to IT assets.</p>{sensitive.length ? <div className="activity-list">{sensitive.map((auction) => <article className="activity-row" key={auction.id}><div><strong>{auction.title}</strong><span>{auction.reference} · {stateLabel(auction.state)}</span></div><div className="activity-value"><strong>{money(auction.currentBid || auction.startingPrice)}</strong>{auction.category === "IT assets" ? <span>{auction.itWipeConfirmed && auction.wipeProofUrl ? "Wipe confirmed" : "Wipe evidence outstanding"}</span> : <span>Sensitive asset review</span>}{auction.wipeProofUrl && <a className="text-link" href={`/api/uploads/download?key=${encodeURIComponent(auction.wipeProofUrl)}`} target="_blank" rel="noreferrer">View certificate</a>}</div></article>)}</div> : <p className="empty-copy">No sensitive assets recorded.</p>}</section>}
    {view === "events" && <section className="workspace-panel"><h2>Audit trail</h2><p className="muted">Latest 100 events. All times are West Africa Time.</p>{events.length ? events.map((event) => <article className="audit-entry" key={event.id}><div className="panel-heading"><strong>{stateLabel(event.action)}</strong><time dateTime={event.createdAt.toISOString()}>{dateTime(event.createdAt)}</time></div><small>{event.auction?.title ?? "System"} · {event.actor?.name ?? "System"} ({stateLabel(event.actorRole ?? event.actor?.role ?? "SYSTEM")})</small>{event.reason && <p>{event.reason}</p>}{(event.before || event.after) && <details><summary>View recorded changes</summary>{event.before && <div><h3>Before</h3><pre>{JSON.stringify(event.before, null, 2)}</pre></div>}{event.after && <div><h3>After</h3><pre>{JSON.stringify(event.after, null, 2)}</pre></div>}</details>}</article>) : <p className="empty-copy">No audit events recorded yet.</p>}</section>}
  </main>;
}
