import Link from "next/link";
import { db } from "@/lib/db";
import { requireOperationsUser } from "@/lib/require-user";
import DisputeActions from "./dispute-actions";
import { canPerform } from "@/lib/permissions";

export default async function AuditPage() {
  const session = await requireOperationsUser();
  const [disputes, events, sensitive] = await Promise.all([db.dispute.findMany({ where: { status: { in: ["OPEN", "UNDER_REVIEW"] } }, include: { auction: true, reporter: { select: { name: true } } }, orderBy: { createdAt: "asc" } }), db.auditEvent.findMany({ include: { auction: true, actor: { select: { name: true, role: true } } }, orderBy: { createdAt: "desc" }, take: 100 }), db.auction.findMany({ where: { sensitive: true }, orderBy: { createdAt: "desc" }, take: 30 })]);
  return <main className="simple-page"><header className="simple-header"><img src="/assets/ffcl_logo_full.png" alt="Fewchore" /><Link href="/operations">← Operations workspace</Link></header><section className="form-page"><p className="eyebrow">COMPLIANCE</p><h1>Disputes and audit trail</h1><h2 className="section-heading">Open disputes</h2><div className="queue-list">{disputes.length === 0 ? <p className="empty-copy">No open disputes.</p> : disputes.map((dispute) => <article className="stacked-card" key={dispute.id}><div><b>{dispute.auction.title}</b><span>{dispute.reason} · Submitted by {dispute.reporter.name}</span><p>{dispute.detail}</p></div>{canPerform(session.user.role, "COMPLIANCE") && <DisputeActions disputeId={dispute.id} />}</article>)}</div><h2 className="section-heading">Sensitive assets</h2><div className="audit-list">{sensitive.map((auction) => <div key={auction.id}><b>{auction.title}</b><span>{auction.reference} · {auction.state.replaceAll("_", " ")} · IT wipe {auction.itWipeConfirmed && auction.wipeProofUrl ? "confirmed" : "not confirmed"} {auction.wipeProofUrl && <a href={`/api/uploads/download?key=${encodeURIComponent(auction.wipeProofUrl)}`} target="_blank" rel="noreferrer">View certificate</a>}</span></div>)}</div><h2 className="section-heading">Recent activity</h2><div className="audit-list">{events.map((event) => <div key={event.id}><b>{event.action.replaceAll("_", " ")}</b><span>{event.auction?.title ?? "System"} · {event.actor?.name ?? "System"} ({event.actorRole ?? event.actor?.role ?? "SYSTEM"}) · {event.createdAt.toLocaleString()}</span>{event.reason && <p>Reason: {event.reason}</p>}{event.before && <pre>Before: {JSON.stringify(event.before)}</pre>}{event.after && <pre>After: {JSON.stringify(event.after)}</pre>}</div>)}</div></section></main>;
}
