"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

export default function SettingsForm({ settings, categories }: { settings: { highValueThreshold: number; defaultPaymentHours: number; defaultPickupDays: number }; categories: { name: string; description: string | null; active: boolean; bundleAllowed: boolean }[] }) {
  const router = useRouter(); const [message, setMessage] = useState("");
  async function save(payload: Record<string, unknown>) { const response = await fetch("/api/admin/settings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json(); setMessage(response.ok ? "Saved." : data.error ?? "Save failed."); if (response.ok) router.refresh(); }
  function submit(event: FormEvent<HTMLFormElement>, kind: string) { event.preventDefault(); const data = new FormData(event.currentTarget); if (kind === "settings") void save({ kind, highValueThreshold: Number(data.get("highValueThreshold")), defaultPaymentHours: Number(data.get("defaultPaymentHours")), defaultPickupDays: Number(data.get("defaultPickupDays")) }); else void save({ kind, name: String(data.get("name")), description: String(data.get("description")), active: data.get("active") === "on", bundleAllowed: data.get("bundleAllowed") === "on" }); }
  return <><form className="listing-form" onSubmit={(event) => submit(event, "settings")}><h2>System settings</h2><label>High-value sensitive threshold (₦)<input name="highValueThreshold" type="number" min="1" defaultValue={settings.highValueThreshold} /></label><div className="two-column"><label>Default payment hours<input name="defaultPaymentHours" type="number" min="1" defaultValue={settings.defaultPaymentHours} /></label><label>Default pickup days<input name="defaultPickupDays" type="number" min="1" defaultValue={settings.defaultPickupDays} /></label></div><button className="primary-button">Save settings</button></form><h2 className="section-heading">Categories</h2><div className="audit-list">{categories.map((item) => <div key={item.name}><b>{item.name}</b><span>{item.active ? "Active" : "Inactive"} · {item.bundleAllowed ? "Lots allowed" : "Single assets"} · {item.description}</span><button className="outline-button" onClick={() => void save({ kind: "category", ...item, active: !item.active })}>{item.active ? "Deactivate" : "Activate"}</button></div>)}</div><form className="listing-form" onSubmit={(event) => submit(event, "category")}><h2>Add category</h2><label>Name<input name="name" required minLength={2} /></label><label>Description<input name="description" /></label><label className="check-label"><input name="active" type="checkbox" defaultChecked /> Active</label><label className="check-label"><input name="bundleAllowed" type="checkbox" /> Allow lots (inventory or scrap only)</label><button className="primary-button">Save category</button></form>{message && <p role="status">{message}</p>}</>;
}
