"use client";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";

type User = { id: string; name: string; email: string; employeeId: string; jobGrade: string; department: string; location: string; role: string; status: string };
const roles = ["EMPLOYEE", "AUCTION_ADMIN", "FINANCE", "FACILITIES", "COMPLIANCE", "SUPER_ADMIN"];
export default function AdminUsers({ users, invitations }: { users: User[]; invitations: { email: string; name: string; usedAt: string | null }[] }) {
  const router = useRouter();
  const [selected, setSelected] = useState<User | null>(null);
  const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setMessage(""); const form = new FormData(event.currentTarget); const values = Object.fromEntries(form.entries()); const response = await fetch("/api/admin/employees", { method: selected ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...values, ...(selected ? { id: selected.id } : {}) }) }); const result = await response.json(); setMessage(response.ok ? selected ? "Profile updated." : "Invitation sent." : result.error ?? "Action failed."); if (response.ok) { setSelected(null); router.refresh(); } }
  return <><form key={selected?.id ?? "invite"} className="listing-form" onSubmit={(event) => void submit(event)}><h2>{selected ? `Edit ${selected.name}` : "Invite an employee"}</h2><div className="two-column"><label>Full name<input name="name" required defaultValue={selected?.name} /></label><label>Company email<input name="email" type="email" required defaultValue={selected?.email} /></label></div><div className="two-column"><label>Employee ID<input name="employeeId" required defaultValue={selected?.employeeId} /></label><label>Grade<input name="jobGrade" required defaultValue={selected?.jobGrade} /></label></div><div className="two-column"><label>Department<input name="department" required defaultValue={selected?.department} /></label><label>Location<input name="location" required defaultValue={selected?.location} /></label></div><div className="two-column"><label>Role<select name="role" defaultValue={selected?.role ?? "EMPLOYEE"}>{roles.map((role) => <option key={role}>{role}</option>)}</select></label>{selected && <label>Status<select name="status" defaultValue={selected.status}><option>ACTIVE</option><option>SUSPENDED</option></select></label>}</div><div className="action-row"><button className="primary-button">{selected ? "Save profile" : "Send invitation"}</button>{selected && <button className="outline-button" type="button" onClick={() => setSelected(null)}>Cancel</button>}</div>{message && <p role="status">{message}</p>}</form><h2 className="section-heading">Employees</h2><div className="audit-list">{users.map((user) => <div key={user.id}><b>{user.name}</b><span>{user.email} · {user.employeeId} · {user.jobGrade} · {user.department} · {user.role} · {user.status}</span><button className="outline-button" onClick={() => setSelected(user)}>Edit</button></div>)}</div><h2 className="section-heading">Invitations</h2><div className="audit-list">{invitations.map((invite) => <div key={invite.email}><b>{invite.name}</b><span>{invite.email} · {invite.usedAt ? "Accepted" : "Pending"}</span></div>)}</div></>;
}
