import Link from "next/link";
import { db } from "@/lib/db";
import { requireOperationsUser } from "@/lib/require-user";

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ from?: string; to?: string; category?: string; location?: string; status?: string; department?: string }> }) {
  await requireOperationsUser();
  const filters = await searchParams;
  const auctions = await db.auction.findMany({ where: { ...(filters.from || filters.to ? { createdAt: { ...(filters.from ? { gte: new Date(filters.from) } : {}), ...(filters.to ? { lte: new Date(`${filters.to}T23:59:59`) } : {}) } } : {}), ...(filters.category ? { category: filters.category } : {}), ...(filters.location ? { location: filters.location } : {}), ...(filters.status ? { state: filters.status as never } : {}), ...(filters.department ? { bids: { some: { bidder: { department: filters.department } } } } : {}) }, include: { pickup: true, payment: true, approval: true }, orderBy: { createdAt: "desc" }, take: 500 });
  const completed = auctions.filter((item) => item.pickup?.completedAt);
  const averageDays = completed.length ? completed.reduce((sum, item) => sum + ((item.pickup?.completedAt?.getTime() ?? 0) - item.createdAt.getTime()) / 86_400_000, 0) / completed.length : null;
  const revenue = auctions.filter((item) => ["PAID", "PICKUP_SCHEDULED", "PICKED_UP", "CLOSED"].includes(item.state)).reduce((sum, item) => sum + (item.payment?.amount ?? 0), 0);
  const sold = auctions.filter((item) => item.approval?.approved).length;
  const stalled = auctions.filter((item) => item.state === "PAYMENT_PENDING" && item.paymentDeadline < new Date()).length;
  const paymentDelays = auctions.filter((item) => item.payment?.submittedAt && item.payment.submittedAt > item.paymentDeadline).length;
  const [rejections, ratings] = await Promise.all([db.auditEvent.groupBy({ by: ["reason"], where: { action: "WINNER_REJECTED", auctionId: { in: auctions.map((item) => item.id) } }, _count: { _all: true } }), db.auctionRating.aggregate({ where: { auctionId: { in: auctions.map((item) => item.id) } }, _avg: { score: true }, _count: { _all: true } })]);
  return <main className="simple-page"><header className="simple-header"><img src="/assets/ffcl_logo_full.png" alt="Fewchore" /><Link href="/operations">← Operations workspace</Link></header><section className="form-page"><p className="eyebrow">MANAGEMENT REPORTS</p><h1>Disposal performance</h1><form className="report-filters"><label>From<input type="date" name="from" defaultValue={filters.from} /></label><label>To<input type="date" name="to" defaultValue={filters.to} /></label><label>Category<input name="category" defaultValue={filters.category} placeholder="All" /></label><label>Location<input name="location" defaultValue={filters.location} placeholder="All" /></label><label>Department<input name="department" defaultValue={filters.department} placeholder="All" /></label><label>Status<select name="status" defaultValue={filters.status ?? ""}><option value="">All</option>{["DRAFT", "PENDING_APPROVAL", "LIVE", "HIGHEST_BID_PENDING_APPROVAL", "PAYMENT_PENDING", "PAID", "PICKUP_SCHEDULED", "PICKED_UP", "CLOSED", "CANCELLED"].map((item) => <option key={item}>{item}</option>)}</select></label><button className="primary-button">Apply filters</button></form><div className="report-grid"><article><span>Listing to pickup</span><strong>{averageDays === null ? "—" : `${averageDays.toFixed(1)} days`}</strong></article><article><span>Assets listed</span><strong>{auctions.length}</strong></article><article><span>Sold / unsold</span><strong>{sold} / {auctions.length - sold}</strong></article><article><span>Revenue recovered</span><strong>₦{revenue.toLocaleString()}</strong></article><article><span>Overdue payments</span><strong>{stalled}</strong></article><article><span>Late proofs</span><strong>{paymentDelays}</strong></article><article><span>Fairness rating</span><strong>{ratings._avg.score?.toFixed(1) ?? "—"} / 5</strong><small>{ratings._count._all} responses</small></article></div><h2 className="section-heading">Winner rejection reasons</h2><div className="audit-list">{rejections.length ? rejections.map((item, index) => <div key={index}><b>{item.reason ?? "Unspecified"}</b><span>{item._count._all} decisions</span></div>) : <p className="empty-copy">No rejected winners in this selection.</p>}</div><h2 className="section-heading">Process bottlenecks</h2><div className="audit-list">{auctions.filter((item) => ["HIGHEST_BID_PENDING_APPROVAL", "PAYMENT_PENDING", "PAID", "PICKUP_SCHEDULED"].includes(item.state)).slice(0, 30).map((item) => <div key={item.id}><b>{item.title}</b><span>{item.state.replaceAll("_", " ")} · Listed {item.createdAt.toLocaleDateString()} · {item.reference}</span></div>)}</div></section></main>;
}
