"use client";

import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { PhotoUpload } from "@/components/photo-upload";
import { EvidenceUpload } from "@/components/evidence-upload";
import { rulesFor } from "@/lib/eligibility";

type Draft = { id: string; title: string; category: string; description: string; condition: string; conditionNotes: string | null; knownDefects: string | null; isLot: boolean; lotItems: string | null; lotQuantity: number | null; lotExclusions: string | null; location: string; assetTag: string | null; tagMissingReason: string | null; photoKeys: string[]; pickupRules: string; paymentRules: string; startingPrice: number; reservePrice: number | null; bidIncrement: number; startsAt: string; endsAt: string; paymentDeadline: string; pickupDeadline: string; antiSniping: boolean; antiSnipingMinutes: number; sensitive: boolean; itWipeConfirmed: boolean; wipeProofUrl: string | null; eligibilityRules: unknown };
const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };
type Options = { grades: string[]; departments: string[]; locations: string[]; employmentStatuses: string[] };
function Choices({ title, name, options, selected }: { title: string; name: string; options: string[]; selected: string[] }) {
  return <fieldset className="choice-group"><legend>{title}</legend>{[...new Set([...options, ...selected])].map(value => <label className="check-label" key={value}><input type="checkbox" name={name} value={value} defaultChecked={selected.includes(value)} />{name === "employmentStatuses" ? value.charAt(0) + value.slice(1).toLowerCase().replaceAll("_", " ") : value}</label>)}{!options.length && !selected.length && <p>No restrictions available. All employees are included.</p>}</fieldset>;
}

export default function ListingForm({ initial, categories, defaults, options }: { options: Options; initial?: Draft; categories: string[]; defaults: { paymentHours: number; pickupDays: number; highValueThreshold: number } }) {
  const router = useRouter();
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);
  const [saved, setSaved] = useState(false);
  const [photoKeys, setPhotoKeys] = useState(initial?.photoKeys ?? []);
  const [uploadsBlocked, setUploadsBlocked] = useState(false);
  const [wipeKey, setWipeKey] = useState<string | null>(initial?.wipeProofUrl ?? null);
  const [wipeBlocked, setWipeBlocked] = useState(false);
  const [categoryChoice, setCategoryChoice] = useState(initial?.category ?? "IT assets");
  const [isLot, setIsLot] = useState(initial?.isLot ?? false);
  const [dirty, setDirty] = useState(false);
  const [startingPrice, setStartingPrice] = useState(initial?.startingPrice ?? 100000);
  const [sensitive, setSensitive] = useState(initial?.sensitive ?? false);
  const originalPhotoKeys = (initial?.photoKeys ?? []).join("\n");
  const updatePhotos = useCallback((keys: string[]) => {
    setPhotoKeys(keys);
    if (keys.join("\n") !== originalPhotoKeys) setDirty(true);
  }, [originalPhotoKeys]);
  useEffect(() => {
    if (!dirty) return;
    const warn = (event: BeforeUnloadEvent) => { event.preventDefault(); };
    window.addEventListener("beforeunload", warn);
    return () => window.removeEventListener("beforeunload", warn);
  }, [dirty]);
  const rules = rulesFor(initial?.eligibilityRules);
  const [now] = useState(() => Date.now());
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (saved || pending) return; setError(""); setPending(true);
    try {
      const values = new FormData(event.currentTarget);
      if (!values.getAll("employmentStatuses").length) throw new Error("Choose at least one eligible employment status.");
      if (uploadsBlocked) throw new Error("Wait for photo uploads to finish, or retry or remove failed photos.");
      const needsWipe = sensitive && categoryChoice === "IT assets";
      if (needsWipe && wipeBlocked) throw new Error("Retry or remove the incomplete wipe certificate upload.");
      const wipeProofUrl = needsWipe ? wipeKey : null;
      const payload = {
        title: String(values.get("title")), category: String(values.get("category")), description: String(values.get("description")), condition: String(values.get("condition")), conditionNotes: String(values.get("conditionNotes")) || null, knownDefects: String(values.get("knownDefects")) || null, isLot: values.get("isLot") === "on", lotItems: String(values.get("lotItems") ?? "") || null, lotQuantity: values.get("lotQuantity") ? Number(values.get("lotQuantity")) : null, lotExclusions: String(values.get("lotExclusions") ?? "") || null,
        location: String(values.get("location")), assetTag: String(values.get("assetTag")) || null, tagMissingReason: String(values.get("tagMissingReason")) || null, photoKeys, pickupRules: String(values.get("pickupRules")), paymentRules: String(values.get("paymentRules")),
        startingPrice: Number(values.get("startingPrice")), reservePrice: values.get("reservePrice") ? Number(values.get("reservePrice")) : null, bidIncrement: Number(values.get("bidIncrement")),
        startsAt: new Date(String(values.get("startsAt"))).toISOString(), endsAt: new Date(String(values.get("endsAt"))).toISOString(), paymentDeadline: new Date(String(values.get("paymentDeadline"))).toISOString(), pickupDeadline: new Date(String(values.get("pickupDeadline"))).toISOString(),
        antiSniping: values.get("antiSniping") === "on", antiSnipingMinutes: Number(values.get("antiSnipingMinutes")), sensitive: values.get("sensitive") === "on", itWipeConfirmed: values.get("itWipeConfirmed") === "on", wipeProofUrl,
        eligibilityRules: { minimumGrade: String(values.get("minimumGrade")) || undefined, departments: values.getAll("departments").map(String), locations: values.getAll("locations").map(String), employmentStatuses: values.getAll("employmentStatuses").map(String), blockUnpaidWins: values.get("blockUnpaidWins") === "on", maximumWins: values.get("maximumWins") ? Number(values.get("maximumWins")) : null, maximumCategoryWins: values.get("maximumCategoryWins") ? Number(values.get("maximumCategoryWins")) : null },
      };
      const response = await fetch(initial ? `/api/operations/auctions/${initial.id}` : "/api/operations/auctions", { method: initial ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "Could not save listing.");
      setDirty(false); setSaved(true); router.push("/operations/listings?saved=1"); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save listing."); } finally { setPending(false); }
  }
  return <main className="simple-page"><section className="form-page"><form id="listing-editor" className="listing-editor" onChange={() => setDirty(true)} onSubmit={(event) => void save(event)}><div className="editor-heading"><div><Link href="/operations/listings">Listings</Link><h1>{initial ? "Edit draft listing" : "Create auction"}</h1></div><div className="editor-actions"><span role="status">{saved ? "Saved. Opening listings…" : pending ? "Saving changes…" : dirty ? "Unsaved changes" : initial ? "Saved draft" : "New draft"}</span><button className="primary-button" disabled={pending || saved || uploadsBlocked || (sensitive && categoryChoice === "IT assets" && wipeBlocked)}>{saved ? "Saved" : pending ? "Saving…" : "Save draft"}</button></div></div>{error && <p className="form-error" role="alert">{error} Your entries are still here; correct the issue and save again.</p>}<fieldset disabled={pending || saved} className="editor-grid"><div className="editor-main"><section className="editor-panel">
    <h2>Asset</h2><label>Title<input name="title" required defaultValue={initial?.title} /></label><div className="two-column"><label>Category<select name="category" defaultValue={initial?.category ?? "IT assets"} onChange={(event) => { setCategoryChoice(event.target.value); if (!["Inventory", "Scrap"].includes(event.target.value)) setIsLot(false); }}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Condition<select name="condition" defaultValue={initial?.condition ?? "Good"}>{["New", "Good", "Fair", "Damaged"].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Description<textarea name="description" required minLength={10} defaultValue={initial?.description} /></label><div className="two-column"><label>Condition notes<textarea name="conditionNotes" defaultValue={initial?.conditionNotes ?? ""} /></label><label>Known defects<textarea name="knownDefects" defaultValue={initial?.knownDefects ?? ""} /></label></div><div className="two-column"><label>Asset tag<input name="assetTag" defaultValue={initial?.assetTag ?? ""} /></label><label>Reason if no tag<input name="tagMissingReason" defaultValue={initial?.tagMissingReason ?? ""} /></label></div><label>Location<input name="location" required defaultValue={initial?.location ?? ""} /></label><PhotoUpload initialKeys={initial?.photoKeys ?? []} onChange={updatePhotos} onBlockedChange={setUploadsBlocked} />
    <p className="photo-hint">Suggested photos: {({ "IT assets": "front, back, screen, ports and serial label", Vehicles: "exterior, interior, odometer, engine bay", Furniture: "front, side and any damage", Machinery: "full view, controls, model plate and defects", Inventory: "overview, contents, quantities and defects", Scrap: "overview, quantity and damage" } as Record<string, string>)[categoryChoice] ?? "overview and defects"}.</p>
    </section>{["Inventory", "Scrap"].includes(categoryChoice) && <section className="editor-panel"><h2>Lots and bundles</h2><label className="check-label"><input name="isLot" type="checkbox" checked={isLot} onChange={event => setIsLot(event.target.checked)} /> This is an inventory or scrap lot</label>{isLot && <div className="lot-fields"><div className="two-column"><label>Item list<textarea name="lotItems" defaultValue={initial?.lotItems ?? ""} /></label><label>Exclusions<textarea name="lotExclusions" defaultValue={initial?.lotExclusions ?? ""} /></label></div><label>Quantity estimate<input name="lotQuantity" type="number" min="1" defaultValue={initial?.lotQuantity ?? ""} /></label>
    </div>}</section>}<section className="editor-panel"><h2>Auction and deadlines</h2><div className="two-column"><label>Starting price (₦)<input name="startingPrice" type="number" min="1" required value={startingPrice} onChange={event => setStartingPrice(Number(event.target.value))} /></label><label>Reserve price (₦, optional)<input name="reservePrice" type="number" min="1" defaultValue={initial?.reservePrice ?? ""} /></label></div><div className="two-column"><label>Bid increment (₦)<input name="bidIncrement" type="number" min="1" required defaultValue={initial?.bidIncrement ?? 10000} /></label><label>Anti-sniping extension (minutes)<input name="antiSnipingMinutes" type="number" min="1" max="30" defaultValue={initial?.antiSnipingMinutes ?? 5} /></label></div><label className="check-label"><input name="antiSniping" type="checkbox" defaultChecked={initial?.antiSniping ?? true} /> Extend close if bid arrives in final minutes</label><div className="two-column"><label>Starts<input name="startsAt" type="datetime-local" required defaultValue={localDate(initial?.startsAt ?? new Date(now + 3600_000).toISOString())} /></label><label>Ends<input name="endsAt" type="datetime-local" required defaultValue={localDate(initial?.endsAt ?? new Date(now + 4 * 86400_000).toISOString())} /></label></div><div className="two-column"><label>Payment deadline<input name="paymentDeadline" type="datetime-local" required defaultValue={localDate(initial?.paymentDeadline ?? new Date(now + 4 * 86400_000 + defaults.paymentHours * 3600_000).toISOString())} /></label><label>Pickup deadline<input name="pickupDeadline" type="datetime-local" required defaultValue={localDate(initial?.pickupDeadline ?? new Date(now + 4 * 86400_000 + defaults.paymentHours * 3600_000 + defaults.pickupDays * 86400_000).toISOString())} /></label></div><label>Payment instructions<textarea name="paymentRules" required minLength={5} defaultValue={initial?.paymentRules ?? "Bank transfer after winner approval. Upload receipt before the deadline."} /></label><label>Pickup instructions<textarea name="pickupRules" required minLength={5} defaultValue={initial?.pickupRules ?? "Facilities will schedule pickup after payment confirmation. Bring employee ID."} /></label>
    </section></div><aside className="editor-side"><section className="editor-panel"><h2>Eligibility</h2><p>Leave departments and locations unchecked to include everyone.</p><div className="two-column"><label>Minimum grade<select name="minimumGrade" defaultValue={rules.minimumGrade ?? ""}><option value="">All grades</option>{[...new Set([...options.grades, ...(rules.minimumGrade ? [rules.minimumGrade] : [])])].map(grade => <option key={grade} value={grade}>{grade} and above</option>)}</select></label><label>Maximum previous wins<input name="maximumWins" type="number" min="0" defaultValue={rules.maximumWins ?? ""} /></label></div><div className="two-column"><Choices title="Departments" name="departments" options={options.departments} selected={rules.departments} /><Choices title="Locations" name="locations" options={options.locations} selected={rules.locations} /></div><div className="two-column"><Choices title="Employment status" name="employmentStatuses" options={options.employmentStatuses} selected={rules.employmentStatuses} /><label>Maximum wins in this category<input name="maximumCategoryWins" type="number" min="0" defaultValue={rules.maximumCategoryWins ?? ""} /></label></div><label className="check-label"><input name="blockUnpaidWins" type="checkbox" defaultChecked={rules.blockUnpaidWins} /> Block employees with overdue unpaid wins</label>
    </section><section className="editor-panel"><h2>Sensitive assets</h2>{startingPrice >= defaults.highValueThreshold && <p className="readiness-note">This asset meets the high-value threshold. Mark it as sensitive before submitting for approval.</p>}<label className="check-label"><input name="sensitive" type="checkbox" checked={sensitive} onChange={event => setSensitive(event.target.checked)} /> Sensitive asset</label>{sensitive && categoryChoice === "IT assets" && <><label className="check-label"><input name="itWipeConfirmed" type="checkbox" defaultChecked={initial?.itWipeConfirmed ?? false} /> IT wipe confirmed</label><EvidenceUpload label="IT wipe certificate" initialKey={wipeKey} onChange={key => { setWipeKey(key); setDirty(true); }} onBlockedChange={setWipeBlocked} /></>}
    </section></aside></fieldset><div className="editor-footer"><span>Save your draft before submitting it for approval.</span><button className="primary-button" disabled={pending || saved || uploadsBlocked || (sensitive && categoryChoice === "IT assets" && wipeBlocked)}>{saved ? "Saved" : pending ? "Saving…" : "Save draft"}</button></div></form></section></main>;
}
