"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { uploadFile } from "@/lib/upload-client";
import { rulesFor } from "@/lib/eligibility";

type Draft = { id: string; title: string; category: string; description: string; condition: string; conditionNotes: string | null; knownDefects: string | null; isLot: boolean; lotItems: string | null; lotQuantity: number | null; lotExclusions: string | null; location: string; assetTag: string | null; tagMissingReason: string | null; photoKeys: string[]; pickupRules: string; paymentRules: string; startingPrice: number; reservePrice: number | null; bidIncrement: number; startsAt: string; endsAt: string; paymentDeadline: string; pickupDeadline: string; antiSniping: boolean; antiSnipingMinutes: number; sensitive: boolean; itWipeConfirmed: boolean; wipeProofUrl: string | null; eligibilityRules: unknown };
const localDate = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); };
const split = (value: FormDataEntryValue | null) => String(value ?? "").split(",").map((part) => part.trim()).filter(Boolean);

export default function ListingForm({ initial, categories, defaults }: { initial?: Draft; categories: string[]; defaults: { paymentHours: number; pickupDays: number } }) {
  const router = useRouter();
  const [error, setError] = useState("");
  const [pending, setPending] = useState(false);
  const [photos, setPhotos] = useState<File[]>([]);
  const [wipeProof, setWipeProof] = useState<File | null>(null);
  const [categoryChoice, setCategoryChoice] = useState(initial?.category ?? "IT assets");
  const rules = rulesFor(initial?.eligibilityRules);
  const now = Date.now();
  async function save(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setError(""); setPending(true);
    try {
      const values = new FormData(event.currentTarget);
      const photoKeys = [...(initial?.photoKeys ?? []), ...(await Promise.all(photos.map(uploadFile)))];
      const wipeProofUrl = wipeProof ? await uploadFile(wipeProof) : initial?.wipeProofUrl ?? null;
      const payload = {
        title: String(values.get("title")), category: String(values.get("category")), description: String(values.get("description")), condition: String(values.get("condition")), conditionNotes: String(values.get("conditionNotes")) || null, knownDefects: String(values.get("knownDefects")) || null, isLot: values.get("isLot") === "on", lotItems: String(values.get("lotItems")) || null, lotQuantity: values.get("lotQuantity") ? Number(values.get("lotQuantity")) : null, lotExclusions: String(values.get("lotExclusions")) || null,
        location: String(values.get("location")), assetTag: String(values.get("assetTag")) || null, tagMissingReason: String(values.get("tagMissingReason")) || null, photoKeys, pickupRules: String(values.get("pickupRules")), paymentRules: String(values.get("paymentRules")),
        startingPrice: Number(values.get("startingPrice")), reservePrice: values.get("reservePrice") ? Number(values.get("reservePrice")) : null, bidIncrement: Number(values.get("bidIncrement")),
        startsAt: new Date(String(values.get("startsAt"))).toISOString(), endsAt: new Date(String(values.get("endsAt"))).toISOString(), paymentDeadline: new Date(String(values.get("paymentDeadline"))).toISOString(), pickupDeadline: new Date(String(values.get("pickupDeadline"))).toISOString(),
        antiSniping: values.get("antiSniping") === "on", antiSnipingMinutes: Number(values.get("antiSnipingMinutes")), sensitive: values.get("sensitive") === "on", itWipeConfirmed: values.get("itWipeConfirmed") === "on", wipeProofUrl,
        eligibilityRules: { minimumGrade: String(values.get("minimumGrade")) || undefined, departments: split(values.get("departments")), locations: split(values.get("locations")), employmentStatuses: split(values.get("employmentStatuses")), blockUnpaidWins: values.get("blockUnpaidWins") === "on", maximumWins: values.get("maximumWins") ? Number(values.get("maximumWins")) : null, maximumCategoryWins: values.get("maximumCategoryWins") ? Number(values.get("maximumCategoryWins")) : null },
      };
      const response = await fetch(initial ? `/api/operations/auctions/${initial.id}` : "/api/operations/auctions", { method: initial ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error ?? "Could not save listing.");
      router.push("/operations/listings"); router.refresh();
    } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save listing."); } finally { setPending(false); }
  }
  return <main className="simple-page"><header className="simple-header"><img src="/assets/ffcl_logo_full.png" alt="Fewchore" /><Link href="/operations/listings">← Listings</Link></header><section className="form-page"><p className="eyebrow">AUCTION ADMIN</p><h1>{initial ? "Edit draft listing" : "Create auction listing"}</h1><form className="listing-form" onSubmit={(event) => void save(event)}>
    <h2>Asset</h2><label>Title<input name="title" required defaultValue={initial?.title} /></label><div className="two-column"><label>Category<select name="category" defaultValue={initial?.category ?? "IT assets"} onChange={(event) => setCategoryChoice(event.target.value)}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><label>Condition<select name="condition" defaultValue={initial?.condition ?? "Good"}>{["New", "Good", "Fair", "Damaged"].map((item) => <option key={item}>{item}</option>)}</select></label></div><label>Description<textarea name="description" required minLength={10} defaultValue={initial?.description} /></label><div className="two-column"><label>Condition notes<textarea name="conditionNotes" defaultValue={initial?.conditionNotes ?? ""} /></label><label>Known defects<textarea name="knownDefects" defaultValue={initial?.knownDefects ?? ""} /></label></div><div className="two-column"><label>Asset tag<input name="assetTag" defaultValue={initial?.assetTag ?? ""} /></label><label>Reason if no tag<input name="tagMissingReason" defaultValue={initial?.tagMissingReason ?? ""} /></label></div><label>Location<input name="location" required defaultValue={initial?.location ?? ""} /></label><label>Asset photos (at least one before approval)<input type="file" accept="image/jpeg,image/png" multiple onChange={(event) => setPhotos(Array.from(event.target.files ?? []))} />{initial?.photoKeys.length ? <small>{initial.photoKeys.length} existing photo(s)</small> : null}</label>
    <p className="photo-hint">Suggested photos: {({ "IT assets": "front, back, screen, ports and serial label", Vehicles: "exterior, interior, odometer, engine bay", Furniture: "front, side and any damage", Machinery: "full view, controls, model plate and defects", Inventory: "overview, contents, quantities and defects", Scrap: "overview, quantity and damage" } as Record<string, string>)[categoryChoice] ?? "overview and defects"}.</p>
    <h2>Lots and bundles</h2><label className="check-label"><input name="isLot" type="checkbox" defaultChecked={initial?.isLot ?? false} /> This is an inventory or scrap lot</label><div className="two-column"><label>Item list<textarea name="lotItems" defaultValue={initial?.lotItems ?? ""} /></label><label>Exclusions<textarea name="lotExclusions" defaultValue={initial?.lotExclusions ?? ""} /></label></div><label>Quantity estimate<input name="lotQuantity" type="number" min="1" defaultValue={initial?.lotQuantity ?? ""} /></label>
    <h2>Auction and deadlines</h2><div className="two-column"><label>Starting price (₦)<input name="startingPrice" type="number" min="1" required defaultValue={initial?.startingPrice ?? 100000} /></label><label>Reserve price (₦, optional)<input name="reservePrice" type="number" min="1" defaultValue={initial?.reservePrice ?? ""} /></label></div><div className="two-column"><label>Bid increment (₦)<input name="bidIncrement" type="number" min="1" required defaultValue={initial?.bidIncrement ?? 10000} /></label><label>Anti-sniping extension (minutes)<input name="antiSnipingMinutes" type="number" min="1" max="30" defaultValue={initial?.antiSnipingMinutes ?? 5} /></label></div><label className="check-label"><input name="antiSniping" type="checkbox" defaultChecked={initial?.antiSniping ?? true} /> Extend close if bid arrives in final minutes</label><div className="two-column"><label>Starts<input name="startsAt" type="datetime-local" required defaultValue={localDate(initial?.startsAt ?? new Date(now + 3600_000).toISOString())} /></label><label>Ends<input name="endsAt" type="datetime-local" required defaultValue={localDate(initial?.endsAt ?? new Date(now + 4 * 86400_000).toISOString())} /></label></div><div className="two-column"><label>Payment deadline<input name="paymentDeadline" type="datetime-local" required defaultValue={localDate(initial?.paymentDeadline ?? new Date(now + 4 * 86400_000 + defaults.paymentHours * 3600_000).toISOString())} /></label><label>Pickup deadline<input name="pickupDeadline" type="datetime-local" required defaultValue={localDate(initial?.pickupDeadline ?? new Date(now + 4 * 86400_000 + defaults.paymentHours * 3600_000 + defaults.pickupDays * 86400_000).toISOString())} /></label></div><label>Payment instructions<textarea name="paymentRules" required minLength={5} defaultValue={initial?.paymentRules ?? "Bank transfer after winner approval. Upload receipt before the deadline."} /></label><label>Pickup instructions<textarea name="pickupRules" required minLength={5} defaultValue={initial?.pickupRules ?? "Facilities will schedule pickup after payment confirmation. Bring employee ID."} /></label>
    <h2>Eligibility</h2><p>Leave a list blank to allow all employees in that field. Use comma-separated values.</p><div className="two-column"><label>Minimum grade<input name="minimumGrade" placeholder="e.g. M3" defaultValue={rules.minimumGrade ?? ""} /></label><label>Maximum previous wins<input name="maximumWins" type="number" min="0" defaultValue={rules.maximumWins ?? ""} /></label></div><div className="two-column"><label>Departments<input name="departments" defaultValue={rules.departments.join(", ")} /></label><label>Locations<input name="locations" defaultValue={rules.locations.join(", ")} /></label></div><div className="two-column"><label>Employment statuses<input name="employmentStatuses" required defaultValue={rules.employmentStatuses.join(", ")} /></label><label>Maximum wins in this category<input name="maximumCategoryWins" type="number" min="0" defaultValue={rules.maximumCategoryWins ?? ""} /></label></div><label className="check-label"><input name="blockUnpaidWins" type="checkbox" defaultChecked={rules.blockUnpaidWins} /> Block employees with overdue unpaid wins</label>
    <h2>Sensitive assets</h2><label className="check-label"><input name="sensitive" type="checkbox" defaultChecked={initial?.sensitive ?? false} /> Sensitive asset</label><label className="check-label"><input name="itWipeConfirmed" type="checkbox" defaultChecked={initial?.itWipeConfirmed ?? false} /> IT wipe confirmed</label><label>IT wipe certificate<input type="file" accept="image/jpeg,image/png,application/pdf" onChange={(event) => setWipeProof(event.target.files?.[0] ?? null)} />{initial?.wipeProofUrl ? <small>Existing certificate uploaded</small> : null}</label>
    {error && <p className="form-error" role="alert">{error}</p>}<button className="primary-button" disabled={pending}>{pending ? "Saving…" : "Save draft listing"}</button></form></section></main>;
}
