"use client";
import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { uploadFile } from "@/lib/upload-client";

export default function EmployeeTasks({ approvals, bids }: { approvals: { auctionId: string; title: string; state: string; paymentStatus: string; pickupStatus: string; pickupAt: string | null; acknowledged: boolean; paymentDeadline: string; pickupDeadline: string; paymentRules: string }[]; bids: { auctionId: string; title: string; amount: number; state: string }[] }) {
  const router = useRouter();
  const [proof, setProof] = useState<Record<string, File | undefined>>({});
  const [message, setMessage] = useState("");
  const [scores, setScores] = useState<Record<string, number>>({});
  async function submit(payload: Record<string, unknown>) { const response = await fetch("/api/workflow", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json(); setMessage(response.ok ? "Saved." : result.error ?? "Action failed."); if (response.ok) router.refresh(); }
  async function submitProof(auctionId: string) { const file = proof[auctionId]; if (!file) { setMessage("Select a JPG, PNG, or PDF receipt first."); return; } try { const key = await uploadFile(file); await submit({ action: "submitPayment", auctionId, proofUrl: key }); } catch (error) { setMessage(error instanceof Error ? error.message : "Upload failed."); } }
  async function rate(auctionId: string) { const response = await fetch("/api/ratings", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ auctionId, score: scores[auctionId] ?? 0 }) }); const data = await response.json(); setMessage(response.ok ? "Feedback saved." : data.error ?? "Could not save feedback."); }
  return <section className="form-page"><p className="eyebrow">EMPLOYEE TASKS</p><h1>Your bids, payments, and pickups</h1><h2 className="section-heading">Approved wins</h2><div className="queue-list">{approvals.length === 0 ? <p className="empty-copy">No approved wins yet.</p> : approvals.map((item) => <article className="stacked-card" key={item.auctionId}><div><b>{item.title}</b><span>{item.state.replaceAll("_", " ")} · Payment: {item.paymentStatus} · Pickup: {item.pickupStatus}</span><span>Payment deadline {new Date(item.paymentDeadline).toLocaleString()} · Pickup deadline {new Date(item.pickupDeadline).toLocaleString()}</span><p>{item.paymentRules}</p>{item.pickupAt && <p>Pickup slot: {new Date(item.pickupAt).toLocaleString()}</p>}</div>{(item.paymentStatus === "PENDING" || item.paymentStatus === "REJECTED") && item.state === "PAYMENT_PENDING" && <div className="proof-form"><input type="file" accept="image/jpeg,image/png,application/pdf" onChange={(event) => setProof({ ...proof, [item.auctionId]: event.target.files?.[0] })} /><button className="primary-button" onClick={() => void submitProof(item.auctionId)}>Upload payment proof</button></div>}{item.state === "PICKED_UP" && !item.acknowledged && <button className="outline-button" onClick={() => void submit({ action: "acknowledgePickup", auctionId: item.auctionId })}>Acknowledge collection</button>}<Link href={`/employee/disputes/new?auctionId=${item.auctionId}`}>Raise a dispute</Link></article>)}</div><h2 className="section-heading">Recent bids</h2><div className="audit-list">{bids.length ? bids.map((bid, index) => <div key={`${bid.auctionId}-${index}`}><b>{bid.title}</b><span>₦{bid.amount.toLocaleString()} · {bid.state === "HIGHEST_BID_PENDING_APPROVAL" ? "Highest bid pending approval" : bid.state.replaceAll("_", " ")}</span>{["CLOSED", "CANCELLED"].includes(bid.state) && <div className="action-row"><select value={scores[bid.auctionId] ?? ""} onChange={(event) => setScores({ ...scores, [bid.auctionId]: Number(event.target.value) })}><option value="">Rate fairness</option>{[1, 2, 3, 4, 5].map((score) => <option key={score} value={score}>{score} / 5</option>)}</select><button className="outline-button" disabled={!scores[bid.auctionId]} onClick={() => void rate(bid.auctionId)}>Save feedback</button></div>}</div>) : <p className="empty-copy">No bids yet.</p>}</div>{message && <p className="form-success">{message}</p>}</section>;
}
