import { db } from "@/lib/db";
import { requireUser } from "@/lib/require-user";
import EmployeeTasks from "./tasks-client";

export default async function TaskWorkspace({ view = "all" }: { view?: "all" | "bids" | "payments" | "pickups" }) {
  const session = await requireUser();
  const approvals = await db.winnerApproval.findMany({ where: { bidderId: session.user.id, approved: true }, include: { auction: { include: { payment: true, pickup: true } } } });
  const bids = await db.bid.findMany({ where: { bidderId: session.user.id }, include: { auction: true }, orderBy: { createdAt: "desc" }, take: 10 });
  return <main className="simple-page"><EmployeeTasks key={view} view={view} approvals={approvals.map((approval) => ({ auctionId: approval.auctionId, approvedAt: approval.createdAt.toISOString(), paidAt: approval.auction.payment?.status === "ACCEPTED" ? approval.auction.payment.reviewedAt?.toISOString() ?? null : null, collectedAt: approval.auction.pickup?.completedAt?.toISOString() ?? null, closedAt: approval.auction.closedAt?.toISOString() ?? null, title: approval.auction.title, reference: approval.auction.reference, amount: approval.auction.payment?.amount ?? approval.auction.currentBid, location: approval.auction.location, paymentReason: approval.auction.payment?.reason ?? null, proofUrl: approval.auction.payment?.proofUrl ?? null, pickupRules: approval.auction.pickupRules, state: approval.auction.state, paymentStatus: approval.auction.payment?.status ?? "PENDING", pickupStatus: approval.auction.pickup?.status ?? "PENDING", pickupAt: approval.auction.pickup?.scheduledAt?.toISOString() ?? null, acknowledged: Boolean(approval.auction.pickup?.acknowledgedAt), paymentDeadline: approval.auction.paymentDeadline.toISOString(), pickupDeadline: approval.auction.pickupDeadline.toISOString(), paymentRules: approval.auction.paymentRules }))} bids={bids.map((bid) => ({ auctionId: bid.auctionId, title: bid.auction.title, amount: bid.amount, state: bid.auction.state }))} /> </main>;
}
